# full list: https://golangci-lint.run/usage/linters/
linters:
  disable-all: true
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - bodyclose
    - contextcheck
    - decorder
    - dupl
    - goconst
    - gocritic
    - gofmt
    - goimports
    - gosec
    - noctx
    - nolintlint
    - prealloc
    - revive
    - stylecheck
    - unconvert
    - usestdlibvars

# full list: https://golangci-lint.run/usage/configuration/
linters-settings:
  staticcheck:
    checks: [ "all" ]
  stylecheck:
    # ignore package comment and naming recommendations
    checks: [ "all", "-ST1000", "-ST1003", "-ST10016"]
  errcheck:
    check-blank: true
  govet:
    shadow: true
  dupl:
    threshold: 500

issues:
  new: true
  new-from-rev: develop

  # Validates whole file instead of changed lines only, but produces many errors
  # on large files. We might consider enabling this flag to start improving the
  # source code file by file. Also, with `whole-files` turned off validators don't
  # check unchanged lines, even if the change leaded to an issue in other place.
  whole-files: false

  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - gosec
        - govet
        - gomnd
        - bodyclose
        - ineffassign

  include:
    - EXC0011
    - EXC0012
    - EXC0014

run:
  go: "1.23"
  allow-parallel-runners: true
  exclude-files:
    - ".*\\.pb\\.go$" # skip protobuf generated code

output:
  formats:
    - format: tab
      path: stderr
