#!/usr/bin/env bash
IMAGE=bloxroute/bxgateway-go-release-candidate:${1:-latest}
PLATFORM=${2:-linux/x86_64}

# extract tag and keep in file (can't be done in docker). Used by Makefile
tag=`git describe --tags --always --dirty --match=v2* 2> /dev/null`
echo $tag > .gittag
echo "Building container... $IMAGE"
docker build  . -f Dockerfile --rm=true --platform $PLATFORM -t $IMAGE
rm .gittag